INSERT INTO amenity (amenity) VALUES ('Extended Hours');
INSERT INTO amenity (amenity) VALUES ('Montessouri');
INSERT INTO amenity (amenity) VALUES ('Special Needs');
INSERT INTO amenity (amenity) VALUES ('Allergy Accomodations');
INSERT INTO amenity (amenity) VALUES ('Play-based');
INSERT INTO amenity (amenity) VALUES ('Extensive Art Programs');
INSERT INTO amenity (amenity) VALUES ('Early Learning');
INSERT INTO amenity (amenity) VALUES ('Hot Meals Included');
INSERT INTO amenity (amenity) VALUES ('Phonics');
INSERT INTO amenity (amenity) VALUES ('Music');
INSERT INTO amenity (amenity) VALUES ('Nap-Time');
INSERT INTO amenity (amenity) VALUES ('Story-Time');
INSERT INTO amenity (amenity) VALUES ('No tablets');
INSERT INTO amenity (amenity) VALUES ('Smoke free');
INSERT INTO amenity (amenity) VALUES ('Covered playgrounds');
INSERT INTO amenity (amenity) VALUES ('Misters for playgrounds');
INSERT INTO amenity (amenity) VALUES ('All teachers college educated');
INSERT INTO amenity (amenity) VALUES ('Open holidays');
INSERT INTO amenity (amenity) VALUES ('Low child to teacher ratio');
INSERT INTO amenity (amenity) VALUES ('Hypo-allergenic cleaning practices');